image: node:18

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  BACKEND_IMAGE: menu-api-image
  FRONTEND_IMAGE: menu-front-image

before_script:
  - npm install -g @prisma/cli

build_backend:
  stage: build
  script:
    - cd apps/api
    - npm install
    - npm run build
    - docker build -t $BACKEND_IMAGE .
  only:
    - main
  tags:
    - menu-runner

build_frontend:
  stage: build
  script:
    - cd apps/web
    - npm install
    - npm run build
    - docker build -t $FRONTEND_IMAGE .
  only:
    - main
  tags:
    - menu-runner

deploy_backend:
  stage: deploy
  script:
    - docker push $BACKEND_IMAGE
  only:
    - main
  tags:
    - menu-runner

deploy_frontend:
  stage: deploy
  script:
    - docker push $FRONTEND_IMAGE
  only:
    - main
  tags:
    - menu-runner